inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
