AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/admin/*

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
