default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stay_home_berlin_development

test:
  <<: *default
  database: stay_home_berlin_test

production:
  <<: *default
  database: stay_home_berlin_production
