default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stay_home_berlin_development

test:
  <<: *default
  database: stay_home_berlin_test

production:
  <<: *default
  database: stay_home_berlin_production
